### PR TITLE
Add basic SwifPM manifest file

### PR DESCRIPTION
**Pull request by Jeehut**
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.

### CODE REVIEW

**Review by OrkhanAlikhanov — COMMENTED** [review]
Looks good I liked the `Accio` project. Is `platforms: [.iOS("8.0")]` something that causes compilation failure in swift package manager but is respected by `Accio`? btw how is that even pronounced?

Merhaba bu arada :)

**Comment by Jeehut** [comment]
The `platforms` line is explained in [this](https://github.com/JamitLabs/Accio#adding-support-for-accio) section of the README, but basically you're right, Accio handles it but it's also handled in Swift 5 therefore when the project will not support Swift 4.2 based projects, you might simply uncomment the line. (But keeping it the way it is right now will work, too, so no worries.)

I have no idea how 'Accio' is officially pronounced, I always read it like it was a latin word so something along "at-chio". In the movie it was pronounced more like "ak-kyo", so you could choose the one you like best. If you're interested in where the name comes from, read more about it [here](https://harrypotter.fandom.com/wiki/Summoning_Charm). Also it's most famous usage is probably in [this scene](https://www.youtube.com/watch?v=ROVjUuAVWyg). ✨ 😉 

Azerbaycan'a selamlar!

**Review by OrkhanAlikhanov — APPROVED** [review]
Looks good!

**Comment by OrkhanAlikhanov** [comment]
@Dschee thank you for such a detailed answer. 

@danieldahan I think it's best to merge this in, I believe Accio will grow as it's backed by Apple's swift package manager and we should let the community enjoy it as early as possible.

**Review by daniel-jonathan — APPROVED** [review]

**Comment by daniel-jonathan** [comment]
@Dschee @OrkhanAlikhanov  thanks guys, it is merged.

**Pull request merged**
